const stops = [
  { name: "Aai Mata Chowk Brts", popular: false },
  { name: "Aai Mata Road", popular: false },
  { name: "Aakash Avenue", popular: false },
  { name: "Aashirwad Doctor House", popular: false },
  { name: "Aaspas Dada Temple Brts", popular: false },
  { name: "Abg Shipyard", popular: false },
  { name: "Abhishek Township", popular: false },
  { name: "Abhva Gaam", popular: false },
  { name: "Abrama Gaam", popular: false },
  { name: "Adajan Gam", popular: false },
  { name: "Adajan Gam Brts", popular: false },
  { name: "Adajan Gsrtc", popular: false },
  { name: "Adarsh Society", popular: false },
  { name: "Adarshnagar Society Kanakpur", popular: false },
  { name: "Agam Shopping Vesu Abhva Road", popular: false },
  { name: "Agarwal Vidhya Vihar", popular: false },
  { name: "Agashi Mata Nu Mandir", popular: false },
  { name: "Ajramar Chowk", popular: false },
  { name: "Akhand Anand College", popular: false },
  { name: "Akhand Anand Park Society", popular: false },
  { name: "Al Amin", popular: false },
  { name: "Alfa Way Bridge Chokdi", popular: false },
  { name: "Alfesani School", popular: false },
  { name: "Alkapuri Circle", popular: false },
  { name: "Althan Bharthana Brts", popular: false },
  { name: "Althan Canal Brts", popular: false },
  { name: "Althan Community Hall", popular: false },
  { name: "Althan Depot/Terminal", popular: false },
  { name: "Althan Khadi Brts", popular: false },
  { name: "Althan Tenament", popular: false },
  { name: "Althan Water Works Junction", popular: false },
  { name: "Amazia Amusement Park Brts", popular: false },
  { name: "Ambedkar Nagar", popular: false },
  { name: "Ambedkar Trust", popular: false },
  { name: "Ambika Nagar Society", popular: false },
  { name: "Amidhara Wadi", popular: false },
  { name: "Amroli Char Rasta", popular: false },
  { name: "Amroli Cross Road", popular: false },
  { name: "Amroli Gaam", popular: false },
  { name: "Anand Dhara Society Mota Varachha", popular: false },
  { name: "Anand Mahal Road Brts", popular: false },
  { name: "Anand Nagar Society", popular: false },
  { name: "Anand Vatika", popular: false },
  { name: "Anand Villa", popular: false },
  { name: "Anjana Health Centre", popular: false },
  { name: "Anjani Boot Bhavani Road Brts", popular: false },
  { name: "Anjani Chowk Mota Varachha", popular: false },
  { name: "Ankur Park Society", popular: false },
  { name: "Anmol Park Society", popular: false },
  { name: "Antroli", popular: false },
  { name: "Anupam Business Hub", popular: false },
  { name: "Anuvrat Dwar Junction (East) Brts", popular: false },
  { name: "Anuvrat Dwar Junction (West) Brts", popular: false },
  { name: "Apex Hospital", popular: false },
  { name: "Apmc Sardar Market Brts", popular: false },
  { name: "Apparel Park Faata", popular: false },
  { name: "Apple Heights", popular: false },
  { name: "Archana Char Rasta", popular: false },
  { name: "Arihant Park", popular: false },
  { name: "Arogya Kendra", popular: false },
  { name: "Arvind Nagar", popular: false },
  { name: "Arya Samaj Marg", popular: false },
  { name: "Ashanagar Masjid Udhana", popular: false },
  { name: "Ashanagar Soiety", popular: false },
  { name: "Ashapura Mata Mandir", popular: false },
  { name: "Asharam Bapu Ashram", popular: false },
  { name: "Ashirwad Enclave Althan Canal Road", popular: false },
  { name: "Ashwanikumar Road", popular: false },
  { name: "Ashwanikumar Smashan Gruh", popular: false },
  { name: "Athwa Pumping Station", popular: false },
  { name: "Athwagate", popular: false },
  { name: "Atop Nagar Bhatar Road", popular: false },
  { name: "Avshar Bungalow", popular: false },
  { name: "Awadh Carolina", popular: false },
  { name: "Awadh Copperstone", popular: false },
  { name: "Ayodhya Nagari Society", popular: false },
  { name: "Azad Chowk", popular: false },
  { name: "B J Patel Cricket Ground", popular: false },
  { name: "B R Park", popular: false },
  { name: "Badrinath Mandir", popular: false },
  { name: "Bahumali", popular: false },
  { name: "Bal Ashram", popular: false },
  { name: "Balaji Farm Vip Road", popular: false },
  { name: "Balaji Mandir", popular: false },
  { name: "Balaji Residency", popular: false },
  { name: "Bamroli", popular: false },
  { name: "Bamroli Khadi", popular: false },
  { name: "Bapa Sitaram Chowk Brts", popular: false },
  { name: "Bapa Sitaram Chowk Yogi Nagar", popular: false },
  { name: "Bapa Sitaram Petrol Pump", popular: false },
  { name: "Baps Hospital Adajan", popular: false },
  { name: "Baps Swaminarayan Sanstha", popular: false },
  { name: "Baps Temple Kanakpur", popular: false },
  { name: "Bapuji Ni Wadi", popular: false },
  { name: "Baroda Pristage Brts", popular: false },
  { name: "Bca College Masma", popular: false },
  { name: "Bhagal", popular: false },
  { name: "Bhagal Char Rasta", popular: false },
  { name: "Bhagat Singh Garden", popular: false },
  { name: "Bhagatalav", popular: false },
  { name: "Bhagirath Apartment", popular: false },
  { name: "Bhagwan Mahavir College", popular: false },
  { name: "Bhagwan Nagar Sarthana", popular: false },
  { name: "Bhagwan Park", popular: false },
  { name: "Bhagwati Society", popular: false },
  { name: "Bhagwatinagar Industrial Estate Brts", popular: false },
  { name: "Bhagyalaxmi Prints", popular: false },
  { name: "Bhagyalaxmi Society", popular: false },
  { name: "Bhagyodaya Society", popular: false },
  { name: "Bhaiya Nagar Brts", popular: false },
  { name: "Bhajiwali Pol", popular: false },
  { name: "Bhakti Dham Brts", popular: false },
  { name: "Bhari Temple", popular: false },
  { name: "Bharthana Brts", popular: false },
  { name: "Bharthana Faata", popular: false },
  { name: "Bharthana Gaam", popular: false },
  { name: "Bharti Maiya School", popular: false },
  { name: "Bhatar Flyover Udhana Magdalla Road", popular: false },
  { name: "Bhatha Gaam", popular: false },
  { name: "Bhathena Canal Junction", popular: false },
  { name: "Bhathena Junction Brts", popular: false },
  { name: "Bhavani Circle", popular: false },
  { name: "Bhesan Gaam", popular: false },
  { name: "Bhesan Gaam Lake", popular: false },
  { name: "Bhestan", popular: false },
  { name: "Bhestan City Bus Depot", popular: false },
  { name: "Bhestan Ews Housing", popular: false },
  { name: "Bhestan Garden", popular: false },
  { name: "Bhestan Naher Brts", popular: false },
  { name: "Bhimpore", popular: false },
  { name: "Bhimpore Faata", popular: false },
  { name: "Bhimrad Gaam Approach", popular: false },
  { name: "Bhindi Bazaar", popular: false },
  { name: "Bhulka Bhavan", popular: false },
  { name: "Bilal Masjid Olpad", popular: false },
  { name: "Bombay Market", popular: false },
  { name: "Brieadliner Circle Udhana Magdalla Road", popular: false },
  { name: "Bsnl Office", popular: false },
  { name: "Bsnl Office Mamta Park", popular: false },
  { name: "Budiya Gaam", popular: false },
  { name: "Budiya Gaam Chokdi", popular: false },
  { name: "Budiya Lake", popular: false },
  { name: "Budiya Rwss", popular: false },
  { name: "CKPithawala EngCollege", popular: false },
  { name: "Canal Junction Vip Road", popular: false },
  { name: "Cancer Hospital Brts", popular: false },
  { name: "Central Ware House Brts", popular: false },
  { name: "Centre For Social Studies Brts", popular: false },
  { name: "Chaapra Bhaatha", popular: false },
  { name: "Chamunda Nagar Society", popular: false },
  { name: "Chandra Shekhar Azad Bridge Approach Katargam", popular: false },
  { name: "Chandramani Society Udhana Magdalla Road", popular: false },
  { name: "Chehar Mata Temple", popular: false },
  { name: "Chhannu Colony Chhaprabhatha", popular: false },
  { name: "Chikuwadi Brts", popular: false },
  { name: "Children Park Adajan", popular: false },
  { name: "Chinagate Brts", popular: false },
  { name: "Chinagate Road Althan Canal Road", popular: false },
  { name: "Chowk Bazar", popular: false },
  { name: "Chowk Terminal", popular: false },
  { name: "City Centre Complex", popular: false },
  { name: "City Centre Puna Gaam", popular: false },
  { name: "City Civic Centre", popular: false },
  { name: "Cj Patel College", popular: false },
  { name: "Colourtex", popular: false },
  { name: "Colourtex Industries", popular: false },
  { name: "Community Hall Utran", popular: false },
  { name: "Corporation School", popular: false },
  { name: "Cyanide Chemicals", popular: false },
  { name: "D Mart Katar Gaam", popular: false },
  { name: "D.G.V.C.L Urja Sadan, Kapodara Brts", popular: false },
  { name: "DIET", popular: false },
  { name: "DRGD High School Sayan", popular: false },
  { name: "Dabholi Char Rasta", popular: false },
  { name: "Dabholi Gaam", popular: false },
  { name: "Dabholi Gaam Approach", popular: false },
  { name: "Dabholi Gam Brts", popular: false },
  { name: "Daksheshwar Mahadev Brts", popular: false },
  { name: "Deep Darshan Vidhya Sankul", popular: false },
  { name: "Delaad Industrial Estate", popular: false },
  { name: "Delaad Patiya", popular: false },
  { name: "Delaad Talaav", popular: false },
  { name: "Deladva Gam", popular: false },
  { name: "Delhi Gate", popular: false },
  { name: "Devashish Nagar Mora Bhagal", popular: false },
  { name: "Dewadh Gaam Faata", popular: false },
  { name: "Dewadh Kumbhariya Aawas", popular: false },
  { name: "Dgvcl Geb Office Palanpur", popular: false },
  { name: "Dgvcl Laskana Brts", popular: false },
  { name: "Dgvcl Mota Varachha", popular: false },
  { name: "Dhanmora / Adajan Patiya Brts", popular: false },
  { name: "Dhruv Park Society", popular: false },
  { name: "Diamond Nagar Brts", popular: false },
  { name: "Diamond Vidhya Sankul Brts", popular: false },
  { name: "Dindayal Society", popular: false },
  { name: "Dindoli Fire Station", popular: false },
  { name: "Dindoli Flower Garden", popular: false },
  { name: "Dindoli Gam", popular: false },
  { name: "Dindoli Kharwasa Road Brts", popular: false },
  { name: "Dindoli Swimming Pool", popular: false },
  { name: "Dindoli Varigruh Brts", popular: false },
  { name: "Diva Farm", popular: false },
  { name: "Dr Shyamaprasad Mukharji Bridge Brts", popular: false },
  { name: "Dr Shyamaprasad Mukharji Lake Garden Brts", popular: false },
  { name: "Dumas Kuvada", popular: false },
  { name: "Dumas Langar", popular: false },
  { name: "Dumbhal Fire Station", popular: false },
  { name: "Dundi Gaam Approach", popular: false },
  { name: "Dutch Garden", popular: false },
  { name: "ESpace Bharthana Vip Road", popular: false },
  { name: "Ecom Warehouse", popular: false },
  { name: "Eden Circle", popular: false },
  { name: "Ekta Nagar", popular: false },
  { name: "Fatakdawadi", popular: false },
  { name: "Fulpada Road Brts", popular: false },
  { name: "Furaja Chowk", popular: false },
  { name: "G 9 Business Centre", popular: false },
  { name: "G D Goenka School", popular: false },
  { name: "GN Pandya College", popular: false },
  { name: "Gabheni Chokdi", popular: false },
  { name: "Gabheni Gaam", popular: false },
  { name: "Gabheni Gaam Approach", popular: false },
  { name: "Gabheni Road", popular: false },
  { name: "Gail India Ltd Vip Road", popular: false },
  { name: "Gajanand Sankul", popular: false },
  { name: "Gajera Circle Brts", popular: false },
  { name: "Galaxy Circle", popular: false },
  { name: "Galaxy Enclave", popular: false },
  { name: "Galemandir Chowk", popular: false },
  { name: "Gandhi College", popular: false },
  { name: "Gandhi Kutir", popular: false },
  { name: "Gandhikutir Junction Udhana Magdalla Road", popular: false },
  { name: "Ganesh Nagar", popular: false },
  { name: "Ganesh Nagar Pandesara", popular: false },
  { name: "Ganeshkrupa Society", popular: false },
  { name: "Ganeshnagar", popular: false },
  { name: "Ganga Jamana Society", popular: false },
  { name: "Gangeshwar Mandir", popular: false },
  { name: "Gaushala Fulpada", popular: false },
  { name: "Gaviyar Gam", popular: false },
  { name: "Gaviyar Vanta", popular: false },
  { name: "Gayatri Mandir", popular: false },
  { name: "Gayatri Mandir Dabholi", popular: false },
  { name: "Gayatri Society", popular: false },
  { name: "Ghanshyam Nagar", popular: false },
  { name: "Ghardi Mata Mandir", popular: false },
  { name: "Giridhardwar Soc Althan Canal Road", popular: false },
  { name: "Girls Polytechnic", popular: false },
  { name: "Global Residency", popular: false },
  { name: "Godadara Gam", popular: false },
  { name: "Godadara School", popular: false },
  { name: "Godadra Canal Junction", popular: false },
  { name: "Godhpur Township", popular: false },
  { name: "Gokuldham", popular: false },
  { name: "Golden Point", popular: false },
  { name: "Gopal Chowk", popular: false },
  { name: "Gopal Nagar", popular: false },
  { name: "Gopi Talav", popular: false },
  { name: "Gopi Talav Market", popular: false },
  { name: "Gotalawadi", popular: false },
  { name: "Gothan Bridge", popular: false },
  { name: "Gothan Vasvaari Faata", popular: false },
  { name: "Goverdhan Nathji Haveli Brts", popular: false },
  { name: "Govindaji Sport Complex", popular: false },
  { name: "Green Avenue", popular: false },
  { name: "Green Avenue", popular: false },
  { name: "Green City", popular: false },
  { name: "Green City Bhatha", popular: false },
  { name: "Green City Bhatha Approach", popular: false },
  { name: "Green Park Brts", popular: false },
  { name: "Green Residency", popular: false },
  { name: "G-Tex Prints", popular: false },
  { name: "Gujarati School Ghod Dod Road", popular: false },
  { name: "Gurukrupa Industries Soc", popular: false },
  { name: "Gwssb Variav", popular: false },
  { name: "Halpati Colony", popular: false },
  { name: "Hamza Apartment", popular: false },
  { name: "Hanuman Tekari", popular: false },
  { name: "Hare Krishna Circle", popular: false },
  { name: "Hare Krishna Circle / Lalita Chokadi Brts", popular: false },
  { name: "Hari Darshan Society Godadara", popular: false },
  { name: "Hari Siddhi Apartment", popular: false },
  { name: "Haridarshan Residency", popular: false },
  { name: "Hidayat Nagar Police Station", popular: false },
  { name: "Hijdawad", popular: false },
  { name: "Hirabaug Brts", popular: false },
  { name: "Hodi Bungalow", popular: false },
  { name: "Honey Park Cross Road", popular: false },
  { name: "Hotel Excellency Icchapor", popular: false },
  { name: "Housing Board Palanpur", popular: false },
  { name: "IC Gandhi School", popular: false },
  { name: "IG Desai School Althan Road", popular: false },
  { name: "IP Mission School", popular: false },
  { name: "Icchanath Mahadev Temple", popular: false },
  { name: "Icchapor Gaam Faata", popular: false },
  { name: "Icchapor Lake", popular: false },
  { name: "Icchapor Town", popular: false },
  { name: "Income Tax", popular: false },
  { name: "Indralok Bunglow Althan Canal Road", popular: false },
  { name: "Ioc Colony Subhash Nagar", popular: false },
  { name: "Iscon Mandir", popular: false },
  { name: "Ishanpor", popular: false },
  { name: "Ishwar Farm Junction Brts", popular: false },
  { name: "Ishwar Nagar Udhana Magdalla Road", popular: false },
  { name: "Iskcon Circle", popular: false },
  { name: "J K P Nagar Society", popular: false },
  { name: "JB Diamond", popular: false },
  { name: "JH Ambani School Brts", popular: false },
  { name: "JT Nagar", popular: false },
  { name: "Jaani Farsaan", popular: false },
  { name: "Jagannathpuri Temple", popular: false },
  { name: "Jagdamba Estate", popular: false },
  { name: "Jagdishchandra Bose Garden", popular: false },
  { name: "Jahangirpura Community Hall Brts", popular: false },
  { name: "Jahangirpura Housing", popular: false },
  { name: "Jai Jogani Mata Chowk Brts", popular: false },
  { name: "Jain Deraasar Amroli", popular: false },
  { name: "Jalaram Society", popular: false },
  { name: "Jalsa Theatre", popular: false },
  { name: "Jamna Nagar Junction Brts", popular: false },
  { name: "Jamna Nagar Society", popular: false },
  { name: "Janki Residency", popular: false },
  { name: "Janta Hospital", popular: false },
  { name: "Jawaharlal Nehru Garden", popular: false },
  { name: "Jay Ambe Society", popular: false },
  { name: "Jay Jalaram Industrial Society", popular: false },
  { name: "Jhansi Ki Rani Garden", popular: false },
  { name: "Jigneshnagar Godadara", popular: false },
  { name: "Jilani Complex", popular: false },
  { name: "Jilani Nagar", popular: false },
  { name: "Jitesh Park Society", popular: false },
  { name: "Jivkor Nagar Bhatar", popular: false },
  { name: "Jivraj 9 Circle Vesu", popular: false },
  { name: "Jj Farm", popular: false },
  { name: "Jolly Residency", popular: false },
  { name: "Jyotindra Dave Garden", popular: false },
  { name: "KP Commerce College", popular: false },
  { name: "Kaadi Faliya Dumas", popular: false },
  { name: "Kaadi Faliya Faata", popular: false },
  { name: "Kabir Mandir Rampura", popular: false },
  { name: "Kadarshah Ni Nal", popular: false },
  { name: "Kadodara", popular: false },
  { name: "Kailash Dham", popular: false },
  { name: "Kailash Nagar Brts", popular: false },
  { name: "Kailash Nagar Dabholi", popular: false },
  { name: "Kakrapar Canal Road", popular: false },
  { name: "Kakrapar Canal Road Junction", popular: false },
  { name: "Kalyan Kutir Society", popular: false },
  { name: "Kamela Darwaja", popular: false },
  { name: "Kamnath Mahadev Brts", popular: false },
  { name: "Kamrej Gsrtc Brts", popular: false },
  { name: "Kamrej Terminal Brts", popular: false },
  { name: "Kanakpur Primary School", popular: false },
  { name: "Kantareshwar Mahadev", popular: false },
  { name: "Kanthariya Hanuman Chowk", popular: false },
  { name: "Kanthariya Hanuman Temple", popular: false },
  { name: "Kapadia Health Club", popular: false },
  { name: "Kapadia Wadi Althan Road", popular: false },
  { name: "Kapodara", popular: false },
  { name: "Kapodara Fire Station Brts", popular: false },
  { name: "Karadva Gam", popular: false },
  { name: "Kargil Chowk Brts", popular: false },
  { name: "Kargil Chowk Puna", popular: false },
  { name: "Karimabad Society Ghod Dod Road", popular: false },
  { name: "Kasba Mohalla Olpad", popular: false },
  { name: "Kaskiwad", popular: false },
  { name: "Katar Gam Gidc", popular: false },
  { name: "Katargam", popular: false },
  { name: "Katargam Brt", popular: false },
  { name: "Katargam Darwaja", popular: false },
  { name: "Katargam Darwaja Brt", popular: false },
  { name: "Katargam Fire Station", popular: false },
  { name: "Katargam Police Station", popular: false },
  { name: "Kathodara Gaam", popular: false },
  { name: "Kathor Gaam", popular: false },
  { name: "Kavi Kalapi Garden", popular: false },
  { name: "Kavi Shree Amrut Ghayal School Variav", popular: false },
  { name: "Keval Circle", popular: false },
  { name: "Khaadi Mohalla Shaala", popular: false },
  { name: "Khadsad Gaam", popular: false },
  { name: "Khajod Gam", popular: false },
  { name: "Kharwarnagar Brts", popular: false },
  { name: "Khatodara Gidc", popular: false },
  { name: "Khatodara Gidc Brts", popular: false },
  { name: "Khatodara Police Station", popular: false },
  { name: "Khatodara Wadi", popular: false },
  { name: "Khatodara Water Works", popular: false },
  { name: "Khodiyar Residency Godadara", popular: false },
  { name: "Khodiyarnagar", popular: false },
  { name: "Khwaja Dana New Road", popular: false },
  { name: "Kinnary Cinema", popular: false },
  { name: "Kiran Hospital", popular: false },
  { name: "Kiran Residency", popular: false },
  { name: "Kosad Bharthana Road", popular: false },
  { name: "Kosad Depot Brts", popular: false },
  { name: "Kosad Ews H1 Brts", popular: false },
  { name: "Kosad Ews H2 Brts", popular: false },
  { name: "Kosad Fire Station Brts", popular: false },
  { name: "Kosad Gam", popular: false },
  { name: "Kosad Housing Board Brts", popular: false },
  { name: "Kosad Talaav", popular: false },
  { name: "Kot Safil Road", popular: false },
  { name: "Krishna Nagar Society", popular: false },
  { name: "Krishna Residency", popular: false },
  { name: "Krishnakunj Society", popular: false },
  { name: "Krishnakunj Society Kanakpur", popular: false },
  { name: "Kshetrapal Mandir", popular: false },
  { name: "Kubernagar", popular: false },
  { name: "Kumbhariya Gaam", popular: false },
  { name: "Kunj Gali", popular: false },
  { name: "Kurukshetra/Rammadhi", popular: false },
  { name: "Kuvawadi", popular: false },
  { name: "Kv Hagrenad Road", popular: false },
  { name: "LN Park Society", popular: false },
  { name: "LP Savani Vidhyabhavan", popular: false },
  { name: "LP Savani", popular: false },
  { name: "Laabheshwar Chowk", popular: false },
  { name: "Ladvi Gam", popular: false },
  { name: "Lajamani Chowk", popular: false },
  { name: "Lajpore Jail", popular: false },
  { name: "Lake View Residency Kosad", popular: false },
  { name: "Lakshimikant Ashram", popular: false },
  { name: "Lal Darwaja", popular: false },
  { name: "Lalgate / Choutapul", popular: false },
  { name: "Lalita Circle", popular: false },
  { name: "Lalwatalaav Olpad", popular: false },
  { name: "Lambe Hanuman Road Brts", popular: false },
  { name: "Lambe Hanuman Temple", popular: false },
  { name: "Lancers Army School Brts", popular: false },
  { name: "Laskana Gam Brts", popular: false },
  { name: "Laxmi Narayan Temple Brts", popular: false },
  { name: "Laxminagar", popular: false },
  { name: "Laxminagar 1", popular: false },
  { name: "Laxminagar Chowk", popular: false },
  { name: "Laxminagar Society", popular: false },
  { name: "Leprosy Hospital", popular: false },
  { name: "Limbayat Health Centre", popular: false },
  { name: "Limda Chowk", popular: false },
  { name: "Linear Bus Stop", popular: false },
  { name: "Lokmanya School Rander", popular: false },
  { name: "Lotus Cricket Academy", popular: false },
  { name: "Luthra Circle Vesu", popular: false },
  { name: "Maakrupa Chemical Industries Ganeshnagar", popular: false },
  { name: "Maan Darwaja", popular: false },
  { name: "Machhiwad", popular: false },
  { name: "Madhav Farm", popular: false },
  { name: "Madhuvan Public School Approach", popular: false },
  { name: "Madina Masjid", popular: false },
  { name: "Madni Society", popular: false },
  { name: "Magdalla Gam Brts", popular: false },
  { name: "Magdalla Port", popular: false },
  { name: "Magdalla T Junction Brts", popular: false },
  { name: "Magob Gam Brt", popular: false },
  { name: "Magob Parvat Khadi Bridge Brts", popular: false },
  { name: "Maha Lakshmi Temple", popular: false },
  { name: "Mahadev Chowk Mota Varachha", popular: false },
  { name: "Mahalaxmi Mandir", popular: false },
  { name: "Maharaja Krushnakumar School", popular: false },
  { name: "Maharana Pratap Bridge / Sai Baba Temple, Dindoli Brts", popular: false },
  { name: "Maharana Pratap Chowk / Devadh Gam Brts", popular: false },
  { name: "Maharana Pratap Garden (Chowpati) Brts", popular: false },
  { name: "Maharana Pratap Junction Brts", popular: false },
  { name: "Maharshi Vedvyas Vidhya Sankul", popular: false },
  { name: "Mahavir Chowk", popular: false },
  { name: "Mahavir Complex Delaad Patiya", popular: false },
  { name: "Mahavir Dhaam Society", popular: false },
  { name: "Mahavir Dham 2", popular: false },
  { name: "Mahavir Heights", popular: false },
  { name: "Mahavir Hospital", popular: false },
  { name: "Mahidharpura Post Office", popular: false },
  { name: "Mahila ITI", popular: false },
  { name: "Majura Gate", popular: false },
  { name: "Majura Gate Fire Station", popular: false },
  { name: "Majuragate Civil Hospital", popular: false },
  { name: "Makbara Masjid", popular: false },
  { name: "Makkai Pool", popular: false },
  { name: "Makkaipool Terminal", popular: false },
  { name: "Malgama Approach", popular: false },
  { name: "Mamta Park Society", popular: false },
  { name: "Man Mandir Apartment", popular: false },
  { name: "Man Sarovar Society", popular: false },
  { name: "Mangal Pandey Hall Brts", popular: false },
  { name: "Mangal Pandey Hall Godadara", popular: false },
  { name: "Maniba Party Plot Vip Road", popular: false },
  { name: "Manoj Singh English Academy", popular: false },
  { name: "Mark Point Dindoli", popular: false },
  { name: "Maruti Dham Society", popular: false },
  { name: "Masma", popular: false },
  { name: "Mastannagar", popular: false },
  { name: "Matawadi Chowk", popular: false },
  { name: "Maulana Azad English School", popular: false },
  { name: "Megnus Alpine Althan Canal Road", popular: false },
  { name: "Meldi Mata Temple", popular: false },
  { name: "Millenium Park", popular: false },
  { name: "Mini Hira Bazaar / Maangadh Chowk Brts", popular: false },
  { name: "Mini Virpur", popular: false },
  { name: "Mini Virpur Temple", popular: false },
  { name: "Mira Nagar Society", popular: false },
  { name: "Mithikhadi Ward Office", popular: false },
  { name: "Model Town Dumbhal", popular: false },
  { name: "Model Town Junction Brts", popular: false },
  { name: "Mora Bhagal", popular: false },
  { name: "Morabhagal Brts", popular: false },
  { name: "Mota Varachha Fire Station", popular: false },
  { name: "Mota Varachha Lake", popular: false },
  { name: "Mota Varachha Prathmik School", popular: false },
  { name: "Mota Varachha Pumping Station", popular: false },
  { name: "Mota Varachha Ward Office", popular: false },
  { name: "Moti Bajar Dumas", popular: false },
  { name: "Moti Talkies", popular: false },
  { name: "Moti Ved", popular: false },
  { name: "Moti Ved Dargah", popular: false },
  { name: "N C Thakkar School", popular: false },
  { name: "Nagar Prathmik School Anjana", popular: false },
  { name: "Nageshwar Temple", popular: false },
  { name: "Nalanda School Vesu Abhva Road", popular: false },
  { name: "Nana Varachha Police Station Brts", popular: false },
  { name: "Nana Varachha Vari Gruh Brts", popular: false },
  { name: "Nandaalay Haveli", popular: false },
  { name: "Nandanvan Row House", popular: false },
  { name: "Nandghar Anganvadi Olpad", popular: false },
  { name: "Nandini Apartment", popular: false },
  { name: "Nandini Flat Vip Road", popular: false },
  { name: "Nandini Residency", popular: false },
  { name: "Nani Bahucharaji Temple", popular: false },
  { name: "Nani Bajar Dumas", popular: false },
  { name: "Nani Ved", popular: false },
  { name: "Nanpura Post Office", popular: false },
  { name: "Narayan Industries Limbayat", popular: false },
  { name: "Narmad Central Library", popular: false },
  { name: "Natvar Nagar", popular: false },
  { name: "Navapara Variav", popular: false },
  { name: "Navin Fluorine Brts", popular: false },
  { name: "Navjivan Circle Udhana Magdalla Road", popular: false },
  { name: "Navsari Bazar", popular: false },
  { name: "Navyug College Brts", popular: false },
  { name: "Nehru Bridge", popular: false },
  { name: "Neminath Nagar Dumbhal", popular: false },
  { name: "New Civil Hospital", popular: false },
  { name: "New Era School", popular: false },
  { name: "Nilgiri Circle", popular: false },
  { name: "Nilkamal Society", popular: false },
  { name: "Nilkanth Society Kapodara", popular: false },
  { name: "Noorani Masjid", popular: false },
  { name: "Noorani Park Society", popular: false },
  { name: "Offira Shopping Vip Road", popular: false },
  { name: "Olpad Bus Depot", popular: false },
  { name: "Olpad College", popular: false },
  { name: "Olpad Court", popular: false },
  { name: "Olpad Gidc", popular: false },
  { name: "Om Complex", popular: false },
  { name: "Om Heritage Dabholi", popular: false },
  { name: "Omkar Row House", popular: false },
  { name: "Ongc Colony Brts", popular: false },
  { name: "Ongc Road Junction", popular: false },
  { name: "Opera City", popular: false },
  { name: "Oxford School", popular: false },
  { name: "Pal Gaam", popular: false },
  { name: "Pal Patiya", popular: false },
  { name: "Pal RTO Brts", popular: false },
  { name: "Palanpur Depot", popular: false },
  { name: "Palanpur Gam", popular: false },
  { name: "Palanpur Gam Talav", popular: false },
  { name: "Palanpur Jakatnaka", popular: false },
  { name: "Palanpur Jakatnaka Circle", popular: false },
  { name: "Palanpur Patiya Brts", popular: false },
  { name: "Palanpur Patiya Circle", popular: false },
  { name: "Palanpur Shala", popular: false },
  { name: "Paliwal Brts", popular: false },
  { name: "Palsana Chokdi", popular: false },
  { name: "Panas Gam Junction Brts", popular: false },
  { name: "Panchmukhi Hanuman Mandir Brts", popular: false },
  { name: "Panchsheel Nagar Anjana", popular: false },
  { name: "Panchtatva", popular: false },
  { name: "Panchvati Garden Icchapor", popular: false },
  { name: "Pandesara", popular: false },
  { name: "Pandesara Industrial Estate", popular: false },
  { name: "Pandesara Industries Estate", popular: false },
  { name: "Pandesara Water Distribution", popular: false },
  { name: "Pandit Dindayal Upadhyay Bhavan, Satyanagar Brts", popular: false },
  { name: "Pandit Shyamji Krishna Verma Bridge Brts", popular: false },
  { name: "Pandol Police Chowki", popular: false },
  { name: "Panjara Pol Ghod Dod Road", popular: false },
  { name: "Param Row House", popular: false },
  { name: "Pardi Kande", popular: false },
  { name: "Parin Gems", popular: false },
  { name: "Parle Point", popular: false },
  { name: "Parle Point Ghod Dod Road", popular: false },
  { name: "Parsiwad", popular: false },
  { name: "Parvat Gam", popular: false },
  { name: "Parvat Gam Brts", popular: false },
  { name: "Parvat Patiya Junction Brts", popular: false },
  { name: "Pasodara Gaam", popular: false },
  { name: "Pasodara Gam Char Rasta Brts", popular: false },
  { name: "Patel Nagar", popular: false },
  { name: "Patel Nagar Society", popular: false },
  { name: "Patel Park", popular: false },
  { name: "Patel Pragati Mandal", popular: false },
  { name: "Patrakar Colony Brts", popular: false },
  { name: "Pipardiwala School", popular: false },
  { name: "Piplod Brts", popular: false },
  { name: "Piplod Main Road", popular: false },
  { name: "Pirchhadi", popular: false },
  { name: "Pisad Pumping Station", popular: false },
  { name: "Piyush Complex", popular: false },
  { name: "Poddar Arcade Varachha", popular: false },
  { name: "Police Commissioner Office", popular: false },
  { name: "Police Lines", popular: false },
  { name: "Pp Savani Sankul", popular: false },
  { name: "Prajapita Brahmakumari Marg / Civil Road, Majurat Fire Station Brts", popular: false },
  { name: "Pramukh Swamy Chowk", popular: false },
  { name: "Pramukh Yog Apartment Dabholi", popular: false },
  { name: "Pramukhchhaya", popular: false },
  { name: "Pranam Residency", popular: false },
  { name: "Pranam Residency 1", popular: false },
  { name: "Prayosha Prime", popular: false },
  { name: "Prem Prakruti Chowk City Light Road", popular: false },
  { name: "Premanand Garden Smc", popular: false },
  { name: "Prime Arcade", popular: false },
  { name: "Priyanka Gold Society", popular: false },
  { name: "Priyanka Green Park Society", popular: false },
  { name: "Priyanka Metro City", popular: false },
  { name: "Priyanka Township", popular: false },
  { name: "Pumping Char Rasta", popular: false },
  { name: "Puna Canal Brts", popular: false },
  { name: "Puna Saroli Junction Brts", popular: false },
  { name: "Puna Talav", popular: false },
  { name: "Punagam Junction Brts", popular: false },
  { name: "Punagam Sarkari Mandli", popular: false },
  { name: "Purushottam Nagar Brts", popular: false },
  { name: "R V Patel Vidhyalay", popular: false },
  { name: "Rachana Circle", popular: false },
  { name: "Rachana Society", popular: false },
  { name: "Radadya Vidhyalaya", popular: false },
  { name: "Radhe Park", popular: false },
  { name: "Radhe Shyam Society Godadara", popular: false },
  { name: "Radhika Point", popular: false },
  { name: "Raghukul Residency", popular: false },
  { name: "Raghuvir Business Hub", popular: false },
  { name: "Raghuvir Row House, Valak Patiya Brts", popular: false },
  { name: "Railway Parcel Office", popular: false },
  { name: "Railway Station Ter", popular: false },
  { name: "Raj Corner", popular: false },
  { name: "Raj Empire Godadara", popular: false },
  { name: "Raj Empire Multiplex", popular: false },
  { name: "Raj Harmony", popular: false },
  { name: "Raj Laxmi Heights", popular: false },
  { name: "Rajhans Tower", popular: false },
  { name: "Ram Nagar", popular: false },
  { name: "Ram Nagar Godadara", popular: false },
  { name: "Rameshwar Nagar", popular: false },
  { name: "Ramnagar Brts", popular: false },
  { name: "Ramnagar Society", popular: false },
  { name: "Ramvatika Society", popular: false },
  { name: "Rander Fire Station", popular: false },
  { name: "Rander Gaam", popular: false },
  { name: "Rander Islam Gymkhana", popular: false },
  { name: "Rander Naher Colony", popular: false },
  { name: "Rangeela Park Ghod Dod Road", popular: false },
  { name: "Rangoli Chokadi", popular: false },
  { name: "Rashmi Kiran Apartment", popular: false },
  { name: "Ratna Jyoti Tower Vesu Abhva Road", popular: false },
  { name: "Ratna Jyoti Tower Vip Road", popular: false },
  { name: "Renuka Bhavan", popular: false },
  { name: "Reshma Nagar", popular: false },
  { name: "Rk Farm Shekhpur", popular: false },
  { name: "Road No 3 Udhana Udhyog Nagar Char Rasta", popular: false },
  { name: "Royal Heritage", popular: false },
  { name: "Royal Platinum", popular: false },
  { name: "Royal Square", popular: false },
  { name: "Royal Township", popular: false },
  { name: "Rukshmani Park Society", popular: false },
  { name: "Rundhnath Mahadev Mandir Brts", popular: false },
  { name: "Rupali Canal Junction Bhatar Road", popular: false },
  { name: "Rupali Junction Brts", popular: false },
  { name: "Rustampura Swimming Pool", popular: false },
  { name: "Ruwaala Tekra", popular: false },
  { name: "S K Park Society Kathodara", popular: false },
  { name: "S M C Health Club", popular: false },
  { name: "SD Planets School", popular: false },
  { name: "SD Jain School Brts", popular: false },
  { name: "SMC Botanical Garden", popular: false },
  { name: "SMC Central Zone Office", popular: false },
  { name: "SMC Kapodara Ward Office Brts", popular: false },
  { name: "SMC North Zone (Katargam) Office Brts", popular: false },
  { name: "SMC Performing Art Centre", popular: false },
  { name: "SMC Sankul", popular: false },
  { name: "SMC Sports Complex", popular: false },
  { name: "SMC Varachha Health Centre, Podar Arcade Brts", popular: false },
  { name: "SMC Water Department", popular: false },
  { name: "SMC West Zone Office Brts", popular: false },
  { name: "SMVS Swaminarayan Temple / Govindaji Hall, Dabholi Brts", popular: false },
  { name: "SMVS Swaminarayan Temple Brts", popular: false },
  { name: "SVNIT Brts", popular: false },
  { name: "Sabar Gaam", popular: false },
  { name: "Sachin Gidc Junction", popular: false },
  { name: "Sachin Gidc Junction Brts", popular: false },
  { name: "Sachin Gidc Naka", popular: false },
  { name: "Sachin Infra", popular: false },
  { name: "Sachin Primary School", popular: false },
  { name: "Sachin Railway Station", popular: false },
  { name: "Sachin Rd No 2 Approach", popular: false },
  { name: "Sachin Rd No 82 Approach", popular: false },
  { name: "Safal Bungalows", popular: false },
  { name: "Sagar Industrial Estate", popular: false },
  { name: "Sagar Society", popular: false },
  { name: "Sagwadi Brts", popular: false },
  { name: "Sahajanand Society Limbayat", popular: false },
  { name: "Sahara Darwaja", popular: false },
  { name: "Sahjanand Estate Dabholi", popular: false },
  { name: "Sahjanand Hills", popular: false },
  { name: "Sahyog Society Sayan", popular: false },
  { name: "Sai Darshan Market", popular: false },
  { name: "Sai Darshan Society Godadara", popular: false },
  { name: "Sai Milaap", popular: false },
  { name: "Sai Petroleum", popular: false },
  { name: "Sai Pujan Residency", popular: false },
  { name: "Sai Shrusti Residency Godadara", popular: false },
  { name: "Sai Square", popular: false },
  { name: "Sainath Society Kanakpur", popular: false },
  { name: "Sainath Society Kapodara", popular: false },
  { name: "Saitirth", popular: false },
  { name: "Saiyedpura Vegetable Market", popular: false },
  { name: "Samarpan Hospital", popular: false },
  { name: "Samata Nagar", popular: false },
  { name: "Samdrasti Park", popular: false },
  { name: "Samrat Industries 1 Godadara", popular: false },
  { name: "Samrat Vidhyalaya Brts", popular: false },
  { name: "Sandya Vadan Society", popular: false },
  { name: "Sangeet Sarita", popular: false },
  { name: "Sangini Skies", popular: false },
  { name: "Saniya Hemad", popular: false },
  { name: "Sanjay Nagar Circle", popular: false },
  { name: "Sanjay Nagar Limbayat", popular: false },
  { name: "Sanjay Society", popular: false },
  { name: "Sanjeev Kumar Auditorium Brts", popular: false },
  { name: "Sanjivani Circle Bhatar", popular: false },
  { name: "Sankalp Residency", popular: false },
  { name: "Sanskar Bhavan", popular: false },
  { name: "Sanskar Industrial Estate", popular: false },
  { name: "Sanskrut Residency", popular: false },
  { name: "Sant Jalaram Society", popular: false },
  { name: "Santosa Heights", popular: false },
  { name: "Santosh Nagar", popular: false },
  { name: "Santro Bakery", popular: false },
  { name: "Saraswati Hindi Vidya Mandir", popular: false },
  { name: "Saraswati Nagar", popular: false },
  { name: "Sardar Chowk", popular: false },
  { name: "Sardar Complex", popular: false },
  { name: "Sardar Patel Society Dabholi", popular: false },
  { name: "Sardar Smruti Bhavan", popular: false },
  { name: "Sargam Shopping Centre", popular: false },
  { name: "Sarjan Avenue Apartment", popular: false },
  { name: "Saroli Brts", popular: false },
  { name: "Saroli Gaam", popular: false },
  { name: "Sarsana Gam", popular: false },
  { name: "Sarthana Naka", popular: false },
  { name: "Sarthana Nature Park Brts", popular: false },
  { name: "Sarvoday Vidhyalay Segvachhama", popular: false },
  { name: "Sashank Park Society", popular: false },
  { name: "Satva Hospital", popular: false },
  { name: "Satyam Residency Puna Gaam", popular: false },
  { name: "Saurabh Police Chowki", popular: false },
  { name: "Saurabh Society", popular: false },
  { name: "Saurashtra Green City", popular: false },
  { name: "Savaliya Circle", popular: false },
  { name: "Savjikorat Bridge", popular: false },
  { name: "Sayan Faata", popular: false },
  { name: "Sayan Railway Station", popular: false },
  { name: "Science Centre City Light Road", popular: false },
  { name: "Sdj School Vesu", popular: false },
  { name: "Second Vip Road Junction", popular: false },
  { name: "Seven Star Residency", popular: false },
  { name: "Seventh Day School", popular: false },
  { name: "Sewage Pumping Mota Varachha", popular: false },
  { name: "Shaarda Vidhya Mandir", popular: false },
  { name: "Shahi Masjid Adajan Gam", popular: false },
  { name: "Shahjanand Apartment", popular: false },
  { name: "Shakti Niketan Mandir", popular: false },
  { name: "Shalidhadra Residency", popular: false },
  { name: "Shamaldham Row House Godadara", popular: false },
  { name: "Shankheshwar Chowk Brts", popular: false },
  { name: "Shantanu Residency Godadara", popular: false },
  { name: "Shanti Kunj", popular: false },
  { name: "Shanti Nagar Row House", popular: false },
  { name: "Shantvan Row House", popular: false },
  { name: "Sharda School", popular: false },
  { name: "Sharda Vidhya Mandir", popular: false },
  { name: "Shayona Park Althan Road", popular: false },
  { name: "Shekhpur Gaam", popular: false },
  { name: "Shiv Bhakti Apartment", popular: false },
  { name: "Shiv Dhara Heights", popular: false },
  { name: "Shiv Industries", popular: false },
  { name: "Shiv Park Residency", popular: false },
  { name: "Shivaji Nagar", popular: false },
  { name: "Shivalik Square", popular: false },
  { name: "Shivdarshan Complex Sachin", popular: false },
  { name: "Shree Darshan Society", popular: false },
  { name: "Shree Gyanjyot Vidhyalay", popular: false },
  { name: "Shree Karamshiram Bapa Ashram", popular: false },
  { name: "Shree Kunj Society", popular: false },
  { name: "Shree Nathji Society Godadara", popular: false },
  { name: "Shree Sahjanand Chowk / Dabholi Char Rasta Brts", popular: false },
  { name: "Shree Sant Kheteshwar Circle / Parvat Patiya Brts", popular: false },
  { name: "Shree Swami Dayanand Saraswati Bridge", popular: false },
  { name: "Shree Swaminarayan Mandir", popular: false },
  { name: "Shree Swaminarayan Mandir Rustom Baug / Ashwinikumar, Fulpada Brts", popular: false },
  { name: "Shreeji Row House Chaapra Bhaatha", popular: false },
  { name: "Shreenath Residency", popular: false },
  { name: "Shreenathaji Haveli Ramnagar", popular: false },
  { name: "Shri Ravishankar Maharaj School", popular: false },
  { name: "Shri Sarjan Palace Vip Road", popular: false },
  { name: "Shrimad Vallabhacharya Chowk / Hirabaug Brts", popular: false },
  { name: "Shrungar Society City Light Road", popular: false },
  { name: "Shukan Sky Apartment", popular: false },
  { name: "Shukan Valley Residency", popular: false },
  { name: "Shyam Dham Chowk Simada", popular: false },
  { name: "Shyam Dham Society Godadara", popular: false },
  { name: "Shyam Mandir Brts", popular: false },
  { name: "Shyam Nagar Brts", popular: false },
  { name: "Shyam Palace", popular: false },
  { name: "Shyam Row House", popular: false },
  { name: "Shyam Shrusti Apartment", popular: false },
  { name: "Shyam Sundar Apartment", popular: false },
  { name: "Shyamdham Mandir Brts", popular: false },
  { name: "Sickon Circle", popular: false },
  { name: "Siddharth Com Junction City Light Road", popular: false },
  { name: "Siddhi Vinayak Residency Sachin", popular: false },
  { name: "Siddhi Vinayak Temple", popular: false },
  { name: "Siddiqui Square", popular: false },
  { name: "Silicon Flats Parvat", popular: false },
  { name: "Silver Palace", popular: false },
  { name: "Silver Stone Homes Dabholi", popular: false },
  { name: "Silverstone Residency", popular: false },
  { name: "Simada Gam", popular: false },
  { name: "Simada Junction Brts", popular: false },
  { name: "Simada Naher Junction Brts", popular: false },
  { name: "Simada Naka", popular: false },
  { name: "Simada Varigruh", popular: false },
  { name: "Singanpore Circle", popular: false },
  { name: "Singanpore STP", popular: false },
  { name: "Singanpore Vegetable Market", popular: false },
  { name: "Sita Nagar", popular: false },
  { name: "Sita Ram Chowk", popular: false },
  { name: "Sitanagar Brts", popular: false },
  { name: "Sky Lark Complex Kapodara", popular: false },
  { name: "Slok Residency", popular: false },
  { name: "Smc Community Hall Khatodara", popular: false },
  { name: "Smc Community Hall Pandesara", popular: false },
  { name: "Smc Community Hall Udhana", popular: false },
  { name: "Smc Garden Godadara", popular: false },
  { name: "Smc Hall Singanpore", popular: false },
  { name: "Smc Library Jahangirpura", popular: false },
  { name: "Smc Night Food Bazaar", popular: false },
  { name: "Smc Party Plot Pal", popular: false },
  { name: "Smc South Zone Office", popular: false },
  { name: "Smc Staff Quarters", popular: false },
  { name: "Smc Ward Office", popular: false },
  { name: "Smc Ward Office 1", popular: false },
  { name: "Smc Ward Office Limbayat", popular: false },
  { name: "Smc Water Works Kosad", popular: false },
  { name: "Smimer Hospital Brt", popular: false },
  { name: "Sneh Nagar Society", popular: false },
  { name: "Sns Square", popular: false },
  { name: "Soham Circle", popular: false },
  { name: "Someshwar Junction Brts", popular: false },
  { name: "Someshwar Nagar 1", popular: false },
  { name: "Someshwara Enclave Vesu Abhva Road", popular: false },
  { name: "Somnath Society Udhana Magdalla Road", popular: false },
  { name: "Sosyo Circle", popular: false },
  { name: "Sosyo Circle Udhana Magdalla Road", popular: false },
  { name: "South Gujarat Medical College", popular: false },
  { name: "Spipa (Surat)", popular: false },
  { name: "Sreepal Nagar Society", popular: false },
  { name: "Sri Ram Petrol Pump", popular: false },
  { name: "Sridhar Society", popular: false },
  { name: "StXavier's High School Ghod Dod Road", popular: false },
  { name: "Star Bazaar", popular: false },
  { name: "Stuti Residency", popular: false },
  { name: "Sub Jail", popular: false },
  { name: "Subhash Garden", popular: false },
  { name: "Sudama Chowk", popular: false },
  { name: "Sukh Sagar", popular: false },
  { name: "Sukhi Nagar", popular: false },
  { name: "Sultanabad", popular: false },
  { name: "Sultanabad Aambawadi", popular: false },
  { name: "Suman Darshan", popular: false },
  { name: "Suman Jyot Ews", popular: false },
  { name: "Suman Keshav Awas", popular: false },
  { name: "Suman Nursery", popular: false },
  { name: "Sumul Dairy", popular: false },
  { name: "Sundarvan Row House", popular: false },
  { name: "Sunrise Vidyalay Dindoli", popular: false },
  { name: "Suraj Mandal Jain Temple", popular: false },
  { name: "Surat Airport", popular: false },
  { name: "Surat Diamond Bourse", popular: false },
  { name: "Surat District Court", popular: false },
  { name: "Surati Ilab", popular: false },
  { name: "Surya Darshan Society", popular: false },
  { name: "Surya Landmark", popular: false },
  { name: "Sushrut Hospital", popular: false },
  { name: "Swagat Society Brts", popular: false },
  { name: "Swami Narayan Gurukul", popular: false },
  { name: "Swami Narayan Mandir (Baps)", popular: false },
  { name: "Swami Narayan Mission - Valak Gam Brts", popular: false },
  { name: "Swaminarayan Chowk Brts", popular: false },
  { name: "Swapna Srusti Residency", popular: false },
  { name: "Swaraj Heights Dabholi", popular: false },
  { name: "Swayam Residency", popular: false },
  { name: "Sweet Home Society", popular: false },
  { name: "Symga School", popular: false },
  { name: "Tadwadi Brts", popular: false },
  { name: "Tadwadi Chhaprabhatha", popular: false },
  { name: "Talad", popular: false },
  { name: "Talawdi Sagrampura", popular: false },
  { name: "Tapash Nagar", popular: false },
  { name: "Tapi Arcade", popular: false },
  { name: "Tapi Society", popular: false },
  { name: "Tapovan Circle", popular: false },
  { name: "Tekrawala School", popular: false },
  { name: "Textile Market", popular: false },
  { name: "Thakordwar Society", popular: false },
  { name: "Tribhuvan Complex Ghod Dod Road", popular: false },
  { name: "Trilok Society", popular: false },
  { name: "Trimurti Apartment", popular: false },
  { name: "Trinity Business Park", popular: false },
  { name: "Tulsidham Brts", popular: false },
  { name: "Udhana Academy College Brts", popular: false },
  { name: "Udhana Darwaja", popular: false },
  { name: "Udhana Darwaja Brts", popular: false },
  { name: "Udhana Gidc Mahatma Gandhi Road", popular: false },
  { name: "Udhana Gidc Road No3", popular: false },
  { name: "Udhana Gsrtc Brts", popular: false },
  { name: "Udhana Railway Station", popular: false },
  { name: "Udhana Road No6 Junction", popular: false },
  { name: "Udhana Teen Rasta Brts", popular: false },
  { name: "Udhana Udhyog Nagar", popular: false },
  { name: "Ugat SMC Water Treatment Plant", popular: false },
  { name: "Ujwaleshwar Mahadev Temple", popular: false },
  { name: "Uma Bhavan Bhatar Road", popular: false },
  { name: "Umabhavan", popular: false },
  { name: "Umiya Chowk", popular: false },
  { name: "Umiya Nagar", popular: false },
  { name: "Umiya Nagar Industrial Estate", popular: false },
  { name: "Umra Food Park", popular: false },
  { name: "Umra Gaam", popular: false },
  { name: "Umra Health Centre", popular: false },
  { name: "Umra Naka", popular: false },
  { name: "Unique Hospital Junction Brts", popular: false },
  { name: "Unn", popular: false },
  { name: "Unn Char Rasta Brts", popular: false },
  { name: "Unn Gam", popular: false },
  { name: "Unn Industrial Estate Brts", popular: false },
  { name: "Unn Naka Brts", popular: false },
  { name: "Utran Lake Garden", popular: false },
  { name: "Utran Power House", popular: false },
  { name: "Utran ROB Bridge Brts", popular: false },
  { name: "Utran Railway Station", popular: false },
  { name: "V T Nagar Road", popular: false },
  { name: "VN Godhani School", popular: false },
  { name: "VNSG University Brts", popular: false },
  { name: "VNSGU Convention Hall Brts", popular: false },
  { name: "VT Choksi College", popular: false },
  { name: "VT Podar College Campus, Pandesara Brts", popular: false },
  { name: "Vaadinath Chowk", popular: false },
  { name: "Vadod Gaam", popular: false },
  { name: "Vadod Gam", popular: false },
  { name: "Vageshwari Temple", popular: false },
  { name: "Vaibhav Chamber", popular: false },
  { name: "Vaishnodevi Heights", popular: false },
  { name: "Vaishnodevi Sky", popular: false },
  { name: "Vaishnodevi Township", popular: false },
  { name: "Vallabhacharya Road Brts", popular: false },
  { name: "Van Bhavan", popular: false },
  { name: "Vanita Vishram", popular: false },
  { name: "Vanita Vishram Ground", popular: false },
  { name: "Vanmali Junction (West) Brts", popular: false },
  { name: "Vanmali Junction Brts", popular: false },
  { name: "Vareli Gaam", popular: false },
  { name: "Variav Gaam", popular: false },
  { name: "Variav Gaam Approach", popular: false },
  { name: "Variyali Bazar Police Chowki", popular: false },
  { name: "Variyav Jakatnaka", popular: false },
  { name: "Vasant Bikha Ni Wadi", popular: false },
  { name: "Vastugram Vip Road", popular: false },
  { name: "Vasu Pujya Apartment", popular: false },
  { name: "Vasvari Gaam", popular: false },
  { name: "Vasvari Lake", popular: false },
  { name: "Vatsalya Bungalows", popular: false },
  { name: "Vatsalya Villa Variyav", popular: false },
  { name: "Vedcha Patia", popular: false },
  { name: "Vedchha Faata", popular: false },
  { name: "Veer Savarkar Circle", popular: false },
  { name: "Velanja Abrama Road", popular: false },
  { name: "Velanja Gaam", popular: false },
  { name: "Velanja Gaam Faata", popular: false },
  { name: "Velanja Gaam Panchayat", popular: false },
  { name: "Venus Estate", popular: false },
  { name: "Verona Residency", popular: false },
  { name: "Vesu Gaam", popular: false },
  { name: "Vichar Kranti Circle", popular: false },
  { name: "Victoria Palm", popular: false },
  { name: "Vidhata Township Parvat", popular: false },
  { name: "Vidhi Bhavan", popular: false },
  { name: "Vidhyakunj", popular: false },
  { name: "Vijay Vallabh Chowk", popular: false },
  { name: "Vindeshwar Mahadev Temple", popular: false },
  { name: "Vip Road Depot", popular: false },
  { name: "Vishal Society Udhana Magdalla Road", popular: false },
  { name: "Vishnu Nagar", popular: false },
  { name: "Vishwakarma Junction Brts", popular: false },
  { name: "Vishwakarma Mandir Brts", popular: false },
  { name: "Vitrag Chemical", popular: false },
  { name: "Vivekanand College", popular: false },
  { name: "Vivekanand Garden", popular: false },
  { name: "Vraj Chowk", popular: false },
  { name: "Vrajvilla Society Shyamnagar", popular: false },
  { name: "Vrudhashram Bhatha", popular: false },
  { name: "Vrukshlaxmi Society", popular: false },
  { name: "Vrundavan Flats", popular: false },
  { name: "Vrundavan Residency Saroli", popular: false },
  { name: "Vrundavan Society Mota Varachha", popular: false },
  { name: "Vrundavan Society Puna", popular: false },
  { name: "Wadi Faliya", popular: false },
  { name: "Weal Park Industries", popular: false },
  { name: "Western City", popular: false },
  { name: "Western City Apartments", popular: false },
  { name: "'Y' Junction Dumas Road Brts", popular: false },
  { name: "'Y' Junction Udhana Magdalla Road Brts", popular: false },
  { name: "Yodi Darshan Society", popular: false },
  { name: "Yogeshwar Park Sachin", popular: false },
  { name: "Yogi Chowk", popular: false },
  { name: "Yogi Nagar Brts", popular: false },
  { name: "Yogi Nagar Society", popular: false },

  { name: "Railway Station Terminal", popular: true },
  { name: "Golden Point", popular: false },
  { name: "Sarthana Nature Park Brts", popular: true },
  { name: "Simadanaka Brts", popular: true },
  { name: "MoraBhagal", popular: false },
  { name: "MoraBhagal Brts", popular: true },
  { name: "ONGC Colony Brts", popular: true },
  { name: "D.G.V.C.L Urja Sadan Brts", popular: true },
  { name: "Someshwar Junction Brts", popular: true },
  { name: "Utran Power House", popular: false },
  { name: "Pandesara Brts", popular: false },
  { name: "Unn Char Rasta Brts", popular: false },
  { name: "Sachin Railway Station", popular: true },
  { name: "Sachin Gidc Junction", popular: true },
  { name: "Navin Fluorine Brts", popular: false },
  { name: "Dindoli Varigruh Brts", popular: false },
  { name: "Jai Jogani Mata Chowk Brts", popular: false },
  { name: "Utran R.O.B Bridge Brts", popular: false },
  { name: "Linear Bus Stop", popular: false },
  { name: "VNSG Convention Hall Brts", popular: false },
  { name: "VNSG University Brts", popular: false },
  { name: "Model Town Dumbhal", popular: false },
  { name: "Model Town Junction Brts", popular: false },
  { name: "Sahara Darwaja", popular: false },
  { name: "Majura gate", popular: false },
  { name: "Maan Darwaja", popular: false },
  { name: "Textile Market", popular: false },
  { name: "Shyam Mandir Brts", popular: true },
  { name: "Devadh Gam Road Brts", popular: false },
  { name: "Althan Khadi Brts", popular: false },
  { name: "Althan Depot Terminal", popular: true },
  { name: "Magob parvat Khadi Bridge Brts", popular: false },
  { name: "Magob Gam Brts", popular: false },
  { name: "Amazia Amusement Park Brts", popular: false },
  { name: "Sitanagar Brts", popular: false },
  { name: "Bharthana Brts", popular: true },
  { name: "Althan Bharthana Brts", popular: false },
  { name: "Anuvrat Dwar Junction (East) Brts", popular: false },
  { name: "Anuvrat Dwar Junction (West) Brts", popular: true },
  { name: "Kharwarnagar Brts", popular: true },
  { name: "Rupali Junction Brts", popular: false },
  { name: "Unique hospital Junction Brts", popular: false },
  { name: "Aaspas Dada Temple Brts", popular: false },
  { name: "Palanpur Patiya Brts", popular: true },
  { name: "Ramnagar Brts", popular: true },
  { name: "Vashnodevi Sky", popular: true },
  { name: "Vashnodevi Heights", popular: true },
  { name: "Vashnodevi Township", popular: true },
  { name: "Jahangirpura Community Hall Brts", popular: true },
  { name: "Jahangirpura Community Hall Brts", popular: true },
];

document.addEventListener("DOMContentLoaded", () => {
  const stopNameContainer = document.querySelector(".stop-names");
  const fromStopInput = document.querySelector(".from-input");
  const toStopInput = document.querySelector(".to-input");

  let stopInputName = "from"; // default focus

  fromStopInput.addEventListener("focus", () => stopInputName = "from");
  toStopInput.addEventListener("focus", () => stopInputName = "to");

  function popularStops() {
    stopNameContainer.innerHTML = "";
    stops.forEach((stop) => {
      if (stop.popular) {
        const p = document.createElement("p");
        p.innerHTML = stop.name;
        p.addEventListener("click", () => addValueInTextbox(stop.name, stopInputName));
        stopNameContainer.appendChild(p);
      }
    });
  }

  function updateStopSuggetion(searchStop, inputFor) {
    const filteredStops = stops.filter(stop =>
      stop.name.toLowerCase().includes(searchStop.toLowerCase())
    );
    updateStopList(filteredStops, inputFor);
  }

  function updateStopList(resultedStops, inputFor) {
    stopNameContainer.innerHTML = "";
    resultedStops.forEach((stop) => {
      const p = document.createElement("p");
      p.innerHTML = stop.name;
      p.addEventListener("click", () => addValueInTextbox(stop.name, inputFor));
      stopNameContainer.appendChild(p);
    });
  }

  function addValueInTextbox(stopName, inputFor) {
    if (inputFor === "from") {
      fromStopInput.value = stopName;
      toStopInput.value = "";
      toStopInput.focus();
      stopInputName = "to";
      popularStops();
    } else if (inputFor === "to") {
      if (fromStopInput.value === "") {
        alert("Please select starting stop first.");
        fromStopInput.focus();
        return;
      }
      toStopInput.value = stopName;

      localStorage.setItem("selectedFromStop", fromStopInput.value);
      localStorage.setItem("selectedToStop", toStopInput.value);
      window.location.href = "https://idyllic-druid-c0a009.netlify.app/index.html";
    }
  }

  // ✅ Enable custom entry (user-typed value) when pressing Enter
  fromStopInput.addEventListener("keypress", function (e) {
    if (e.key === "Enter") {
      if (fromStopInput.value.trim()) {
        addValueInTextbox(fromStopInput.value.trim(), "from");
      }
    }
  });

  toStopInput.addEventListener("keypress", function (e) {
    if (e.key === "Enter") {
      if (toStopInput.value.trim()) {
        addValueInTextbox(toStopInput.value.trim(), "to");
      }
    }
  });

  fromStopInput.addEventListener("input", (e) => {
    updateStopSuggetion(e.target.value, "from");
  });

  toStopInput.addEventListener("input", (e) => {
    updateStopSuggetion(e.target.value, "to");
  });

  popularStops();
});
